theme: jekyll-theme-cayman
title: Dev Client
description: Dev Client the remake of the original Jello
show_downloads: true
github:
  zip_url: http://example.com/download.zip
  another_url: another value
